import type { Beat } from "@caller/core";
import type { MotionReport, MotionStats } from "@caller/choreo";
import {
  MOTION_STEP,
  createTimeline,
  formatMotionReport,
  motionReport,
  withDefaults,
} from "@caller/choreo";
import {
  CONTRA_EVENNESS,
  CONTRA_MOTION_BOUNDS,
  CONTRA_TAKE_MOTION,
  CONTRA_TRAVEL_MOTION,
  GUARD_FACTOR,
  TRAVEL_GUARD_FACTOR,
} from "./motionBounds.js";
import { checkGroup, figureChecks } from "./figureChecks.js";
import { KNOWN_WRONG, isKnownWrong } from "./knownWrong.js";
import { createContraRegistry } from "./registry.js";
import { DEMO_DANCES } from "../dances/index.js";
import { danceAlone, linesFor } from "../dances/oracle.js";
import { dataOnlyFigureIds } from "../library/figures/index.js";
import type { AnyFigureDef } from "@caller/choreo";
import { figureOnFour } from "./onFour.js";
import { LAB_RUN } from "../dances/danceLab.js";
import { isBecket } from "../dances/formations.js";

/**
 * `docs/motion-report.md`: the whole instrument, as one page somebody can read
 * on a phone.
 *
 * It is pure — it returns a string and writes nothing — so it can be tested
 * and so the file writing stays in `scripts/reportMotion.mjs`, which is what
 * `pnpm report:motion` runs.
 */

/** How long each dance is measured for: two times through. */
export const REPORT_BEATS: Beat = 128;

/** How many rows of each table the report prints. */
export const REPORT_ROWS = 10;

/** The whole report, as markdown. */
export function motionReportMarkdown(): string {
  const out: string[] = [];
  out.push("# The motion report");
  out.push("");
  out.push(
    "Generated by `pnpm report:motion` (F3a). It measures how the **drawn arm** moves — " +
      "the hand and the elbow the renderer actually puts on the screen, through " +
      "`@caller/core`'s `drawnArms` — over every demo dance and every figure in the " +
      "registry, and checks each figure against what a caller would say it does.",
  );
  out.push("");
  out.push("Nothing in here is a pass/fail gate. It is the thing to read before fixing a figure.");
  out.push("");

  out.push(...boundsSection());
  out.push(...dancesSection());
  out.push(...figuresSection());
  out.push(...knownWrongSection());
  out.push(...checksSection());
  out.push(...describeSection());
  return out.join("\n") + "\n";
}

/** Where the bounds came from. */
function boundsSection(): string[] {
  const take = CONTRA_TAKE_MOTION;
  return [
    "## The bounds, and how they were derived",
    "",
    "The bounds are **derived, not picked**. The fastest legitimate hand motion in the",
    "library is a *take*: a hand leaves the dancer's hip and arrives at a joined point",
    "over one beat, with `takeAndRelease`'s own smoothstep ramp (`holdWindow(beats, 1, 1)`",
    "gives a one-beat take for every figure of four beats or more). Everything else — a",
    "swing's orbit, a hey's lane, a chain's pull by — moves a hand no faster than a body",
    "walks.",
    "",
    "So: measure the worst take the registry actually contains, then guard at " +
      `**${GUARD_FACTOR}×** it.`,
    "",
    `- The furthest any figure reaches from a dancer's own hip to a hand they hold is **${take.floorPx.toFixed(4)} px** (\`${take.floorAt}\`).`,
    `- The lowest drop any figure holds a hand at is **${take.drop} px** (\`${take.dropAt}\`), so the largest lift a take makes is 14.5 px.`,
    "- Measured at 1/32 beat, a standing dancer's one-beat take over that geometry peaks at:",
    "",
    "| | legitimate maximum | × 3 = the bound |",
    "| --- | ---: | ---: |",
    `| hand floor speed | ${take.handSpeed.toFixed(4)} px/beat | **${CONTRA_MOTION_BOUNDS.handSpeedPx.toFixed(4)}** |`,
    `| elbow floor speed | ${take.elbowSpeed.toFixed(4)} px/beat | **${CONTRA_MOTION_BOUNDS.elbowSpeedPx.toFixed(4)}** |`,
    `| elbow speed ÷ hand speed, per sample | ${take.elbowRatio.toFixed(4)}× | **${CONTRA_MOTION_BOUNDS.elbowPerHand.toFixed(4)}** |`,
    `| hand height rate | ${take.heightRate.toFixed(4)} px/beat | **${CONTRA_MOTION_BOUNDS.heightRatePx.toFixed(4)}** |`,
    `| out-and-back inside one beat | ${take.hangingDipPx.toFixed(4)} px | **${CONTRA_MOTION_BOUNDS.dipPx.toFixed(4)}** |`,
    "",
    "The dip bound comes from the one out-and-back the model asks for: a hanging hand",
    "swings forward and back once a beat, `2 × HAND_HANG_SWING_PX` = 1.2 px.",
    "",
    "### The sustained-travel bound (M10, R6)",
    "",
    "Every column above is about a **drawn arm**, and a figure can pass all of them while",
    "walking its dancers across the hall at a run. `travel` is the one column about the",
    "body: the fastest any dancer moves, averaged over a sliding **one-beat window**.",
    "Sustained, not instantaneous — a beat is the unit a count is written in, and what",
    "separates a walk from a take is that a take is over inside one.",
    "",
    "Its guard is **" +
      `${TRAVEL_GUARD_FACTOR}×**, not 3×: the reference is the swing's own orbit at ` +
      `**${CONTRA_TRAVEL_MOTION.travelPx.toFixed(4)} px/beat** ` +
      `(\`${CONTRA_TRAVEL_MOTION.travelAt}\`), which gives a bound of ` +
      `**${CONTRA_MOTION_BOUNDS.travelPx.toFixed(4)} px/beat**. A walk faster than one and`,
    "a half swings is a run, where three times an honest take is still obviously a take.",
    "",
    "The fastest figure run alone is **not** the reference: `" +
      `${CONTRA_TRAVEL_MOTION.fastestId}\` reaches ${CONTRA_TRAVEL_MOTION.fastestPx.toFixed(4)} px/beat,` +
      " and it is a two-beat figure probed outside the line of four it is danced in. A",
    "guard at 1.5 × that would be a guard nothing in the library could ever trip.",
    "See `figures/motionBounds.ts` for the derivation and the whole ranking, and",
    "`dances/motionAllowlist.ts` for the rows a dance is allowed to be over it on.",
    "",
    "### The evenness bound (M10b)",
    "",
    "`travel` is a peak, and a peak cannot see a figure where one role sprints while",
    "another strolls, because neither of them need be fast. Two columns do:",
    "**`roles`** is the fastest role's mean speed over the whole figure divided by the",
    "slowest's, and **`halves`** is one dancer's faster half of a figure divided by their",
    'slower half. The user, judging the chain: *"people try to move at a constant speed',
    'throughout the moves for the most part."* So the ideal of both is **1.00**.',
    "",
    "Their bound is the **floor's own aspect**, and it is the one bound here with no guard",
    `factor on top: **${CONTRA_EVENNESS.spread.toFixed(2)}×**, which is the minor set's own rectangle — ` +
      `${String(CONTRA_EVENNESS.acrossPx)} px across the set`,
    `against ${String(CONTRA_EVENNESS.alongPx)} px along it, the same in duple improper, proper and becket. Four`,
    "dancers standing on those four places cannot be sent round them evenly: a figure that",
    "walks the rectangle *must* spread its roles in the ratio of its two sides. `petronella`,",
    "which is exactly that figure, measures 1.5455 run alone, and " +
      `\`${CONTRA_EVENNESS.witnessId}\` ${CONTRA_EVENNESS.witnessSpread.toFixed(4)} — both`,
    "just under the aspect, which is the evidence that the aspect is the ceiling the floor",
    "imposes rather than a number picked to clear them.",
    "",
    "A guard factor would be a licence rather than a guard here. Every other bound above",
    "multiplies a *magnitude*; this is a **ratio whose ideal is 1**, and three times it",
    "would permit a figure to walk one role nearly five times as fast as another. The",
    "headroom is in the reference instead. Neither column is measured on a **seam** row —",
    "a seam is half of each of two figures and a mean over half a figure is not one — so a",
    "seam shows `—`, which is not `1.00`.",
    "",
    "**The elbow bound F3a derived was useless, and F3c found out why.** A take moved the",
    "elbow at 250 px/beat — 9.33× the hand — which put the guard at 750 px/beat, a number",
    "nothing would ever trip. That was not the elbow being unbounded by construction: it",
    "was the elbow **pole lining up with the arm** part way through the take, and the elbow",
    "flipping through 180° as it crossed. With the pole capped",
    `(\`ELBOW_POLE_ALONG_FRACTION\` in \`@caller/core\`) the same take moves the elbow at ${take.elbowSpeed.toFixed(1)}`,
    `px/beat, **${take.elbowPerHand.toFixed(3)}×** the hand, and the guard means something again.`,
    "",
    "The **ratio** is the column that discriminates, and it is derived the same way: the",
    "worst per-sample `elbow speed ÷ hand speed` an honest take produces, with the hand",
    "floored at `STILL_HAND_PX` (2π × `HAND_HANG_SWING_PX` = 3.77 px/beat, the fastest a",
    "hand moves while its dancer stands still) so an elbow that swings while the hand is",
    "stationary is still counted against it.",
    "",
    "The **jump** column is the distance a hand moved in the step where its state flipped",
    "between placed and hanging. A flip is not itself a defect — a hand a figure placed and",
    "the next figure leaves `'down'` really does stop being placed — but before F3c the seam",
    "switched the two at its midpoint and the hand jumped the whole way between them. It is",
    "marked against one step of the hand's own bound.",
    "",
    "These are **guards**, not tuning targets: at 1.05× they would flake on the first",
    "figure anybody re-tuned. `motionBounds.test.ts` re-derives every number above and",
    "fails if the code moves under it.",
    "",
  ];
}

/** The motion oracle over the demo dances. */
function dancesSection(): string[] {
  const out: string[] = ["## Over the demo dances", ""];
  out.push(
    `Each dance run alone by the script decider for two times through (beats 0–${REPORT_BEATS}), ` +
      "duple improper and proper at 4 couples and becket at 6, sampled every 1/32 beat.",
    "",
  );

  const figures = new Map<string, MotionStats>();
  const seams = new Map<string, MotionStats>();
  let overall: MotionStats | undefined;
  for (const dance of DEMO_DANCES) {
    const couples = linesFor(dance).includes(6) && isBecket(dance) ? 6 : 4;
    // **On the engine the dance ships on**, which since M11 is the only one
    // there is. This report used to measure every dance written before M5 on
    // the decider's own planner and the rest on the contra planner, because the
    // two differed by up to 1.16 px at the ends of a line (M3's cycle-start
    // switch) and switching them all over was a rewrite rather than a
    // milestone's business. The coded layer the old planner needed is deleted,
    // so the whole table is the shipped path now — which is what it should
    // always have been measuring.
    const decider = danceAlone(dance, couples, REPORT_BEATS, {}, LAB_RUN);
    const report = motionReport(decider.timeline(), REPORT_BEATS, {
      bounds: CONTRA_MOTION_BOUNDS,
    });
    for (const row of report.figures) merge(figures, row);
    for (const row of report.seams) merge(seams, row);
    overall = overall ? mergeInto(overall, report.overall) : { ...report.overall };
  }

  out.push(
    "### The ten worst figures",
    "",
    ...table([...figures.values()].sort(worstFirst).slice(0, REPORT_ROWS)),
    "",
    "### The ten worst seams",
    "",
    ...table([...seams.values()].sort(worstFirst).slice(0, REPORT_ROWS)),
    "",
  );
  if (overall) {
    out.push(
      `Over all ten dances: ${overall.samples.toLocaleString("en-GB")} measurements, ` +
        `${overall.stateFlips} hand-state flips, **${overall.nonFinite} of them not a finite number**.`,
      "",
    );
  }
  return out;
}

/** The motion oracle over each figure of the registry, alone. */
function figuresSection(): string[] {
  const out: string[] = ["## Every figure, alone", ""];
  out.push(
    "Each figure run on its own in a duple improper group of four, with nothing before",
    "it, so every number is the figure's own and no seam is folded in.",
    "",
  );
  out.push(...table(figureAloneRows()));
  out.push("");
  return out;
}

/**
 * One figure on its own timeline, measured; worst first.
 *
 * Every coded figure, and since M5 the **data-only** ones the hands-four
 * template can plan too — the hey among them, whose coded twin this milestone
 * deleted. A figure resolution mints per pair (`pull-by`, `shoulder-round`) or
 * over a whole line (`grand-right-and-left`) cannot be run on a group of four
 * and is not in this table; M7's shapes with named places are what would give
 * those a figure-alone row.
 */
export function figureAloneRows(): MotionStats[] {
  const rows: MotionStats[] = [];
  for (const id of dataOnlyFigureIds()) {
    // **Whatever a hands-four can plan** (M11). It used to be the coded
    // figures plus the data-only ones a bare template could plan; the coded
    // ones are gone and `figureOnFour` is the one predicate left — it mints the
    // pair instances a minor set implies, so the swing and its kind keep the
    // row their coded twins used to give them.
    const alone = figureOnFour(id);
    if (alone === undefined) continue;
    const registry = createContraRegistry([alone as AnyFigureDef]);
    const def = registry.get(id);
    const group = checkGroup();
    const timeline = createTimeline(registry);
    timeline.addGroup(group);
    const bindings: Record<string, string> = {};
    for (const station of group.stations) bindings[station.id] = station.id;
    timeline.add({
      kind: "figure",
      group: group.id,
      figure: id,
      params: withDefaults(def, {}, def.beats),
      bindings,
      start: 0,
      end: def.beats,
    });
    const report = motionReport(timeline, def.beats, { bounds: CONTRA_MOTION_BOUNDS });
    const row = report.figures[0];
    if (row) rows.push(row);
  }
  return rows.sort(worstFirst);
}

/** The known-wrong table. */
function knownWrongSection(): string[] {
  const out: string[] = ["## Known wrong", ""];
  out.push(
    "Every assertion below fails today and is **expected** to. The contract the tests",
    "hold is that everything *not* on this list passes and everything *on* it still",
    "fails, so a fix has to delete its row. Nothing is skipped; nothing was loosened.",
    "",
    "| figure or seam | assertion | measured | why |",
    "| --- | --- | --- | --- |",
  );
  for (const row of KNOWN_WRONG) {
    out.push(`| \`${row.key}\` | ${row.label} | ${row.measured} | ${row.why} |`);
  }
  out.push("");
  return out;
}

/** Every trajectory assertion, with its evidence. */
function checksSection(): string[] {
  const out: string[] = ["## What each figure actually does", ""];
  for (const group of figureChecks()) {
    out.push(`### \`${group.key}\``);
    out.push("");
    if (group.describe) {
      out.push(`> ${group.describe}`);
      out.push("");
    }
    out.push("| | assertion | evidence |");
    out.push("| --- | --- | --- |");
    for (const result of group.results) {
      const mark = result.pass
        ? "pass"
        : isKnownWrong(group.key, result.label)
          ? "**known**"
          : "**FAIL**";
      out.push(`| ${mark} | ${result.label} | ${result.note} |`);
    }
    out.push("");
  }
  return out;
}

/** The `describe` of every figure in the registry, and which are unsure. */
function describeSection(): string[] {
  const registry = createContraRegistry();
  const out: string[] = ["## What every figure says it does", ""];
  out.push(
    "These are the specifications the assertions above are written against. Anything",
    "marked `(unsure: …)` is a guess a caller should correct.",
    "",
  );
  for (const id of registry.ids().sort()) {
    const def = registry.get(id);
    out.push(`### \`${id}\` — ${def.call}`);
    out.push("");
    out.push(def.describe ?? "_no description._");
    out.push("");
  }
  return out;
}

/** Merge one dance's row into the running total for that key. */
function merge(rows: Map<string, MotionStats>, row: MotionStats): void {
  const found = rows.get(row.key);
  if (!found) {
    rows.set(row.key, { ...row });
    return;
  }
  rows.set(row.key, mergeInto(found, row));
}

/** The worse of two rows, field by field. */
function mergeInto(a: MotionStats, b: MotionStats): MotionStats {
  const worse = <
    K extends
      | "handSpeed"
      | "elbowSpeed"
      | "elbowPerHand"
      | "heightRate"
      | "travel"
      | "roleSpread"
      | "partSpread"
      | "elbowHeightRate"
      | "flipJump"
      | "dip",
  >(
    key: K,
  ) => (b[key].value > a[key].value ? b[key] : a[key]);
  return {
    key: a.key,
    handSpeed: worse("handSpeed"),
    elbowSpeed: worse("elbowSpeed"),
    elbowPerHand: worse("elbowPerHand"),
    heightRate: worse("heightRate"),
    travel: worse("travel"),
    roleSpread: worse("roleSpread"),
    partSpread: worse("partSpread"),
    elbowHeightRate: worse("elbowHeightRate"),
    flipJump: worse("flipJump"),
    dip: worse("dip"),
    stateFlips: a.stateFlips + b.stateFlips,
    ...((a.firstFlip ?? b.firstFlip) ? { firstFlip: a.firstFlip ?? b.firstFlip } : {}),
    nonFinite: a.nonFinite + b.nonFinite,
    ...((a.firstNonFinite ?? b.firstNonFinite)
      ? { firstNonFinite: a.firstNonFinite ?? b.firstNonFinite }
      : {}),
    reversals: a.reversals + b.reversals,
    samples: a.samples + b.samples,
  };
}

/** Worst first, by how far each row is over its bound. */
function worstFirst(a: MotionStats, b: MotionStats): number {
  return severity(b) - severity(a) || a.key.localeCompare(b.key);
}

function severity(s: MotionStats): number {
  return Math.max(
    s.handSpeed.value / CONTRA_MOTION_BOUNDS.handSpeedPx,
    s.elbowSpeed.value / CONTRA_MOTION_BOUNDS.elbowSpeedPx,
    s.elbowPerHand.value / CONTRA_MOTION_BOUNDS.elbowPerHand,
    s.heightRate.value / CONTRA_MOTION_BOUNDS.heightRatePx,
    s.travel.value / CONTRA_MOTION_BOUNDS.travelPx,
    s.roleSpread.value / CONTRA_MOTION_BOUNDS.spread,
    s.partSpread.value / CONTRA_MOTION_BOUNDS.spread,
    s.dip.value / CONTRA_MOTION_BOUNDS.dipPx,
    s.stateFlips > 0 ? 1 : 0,
    s.nonFinite > 0 ? 1000 : 0,
  );
}

const HEADER = [
  "| what | hand px/beat | elbow px/beat | elbow/hand | height px/beat | travel px/beat | roles × | halves × | flips | jump px | NaN | dip px | worst hand at |",
  "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
];

function table(rows: readonly MotionStats[]): string[] {
  if (rows.length === 0) return ["_nothing measured._"];
  return [
    ...HEADER,
    ...rows.map(
      (r) =>
        `| \`${r.key}\` | ${over(r.handSpeed.value, CONTRA_MOTION_BOUNDS.handSpeedPx)} | ` +
        `${over(r.elbowSpeed.value, CONTRA_MOTION_BOUNDS.elbowSpeedPx)} | ` +
        `${over(r.elbowPerHand.value, CONTRA_MOTION_BOUNDS.elbowPerHand, 2)} | ` +
        `${over(r.heightRate.value, CONTRA_MOTION_BOUNDS.heightRatePx)} | ` +
        `${over(r.travel.value, CONTRA_MOTION_BOUNDS.travelPx)} | ` +
        `${spread(r.roleSpread.value)} | ${spread(r.partSpread.value)} | ${r.stateFlips} | ` +
        `${over(r.flipJump.value, CONTRA_MOTION_BOUNDS.handSpeedPx * MOTION_STEP, 2)} | ` +
        `${r.nonFinite} | ${over(r.dip.value, CONTRA_MOTION_BOUNDS.dipPx, 2)} | ${where(r)} |`,
    ),
  ];
}

/** A number, marked when it is over its bound. */
const over = (value: number, bound: number, places = 1): string =>
  value > bound ? `**${value.toFixed(places)}**` : value.toFixed(places);

/** A spread, marked when it is over the one bound the two share; `—` unmeasured. */
const spread = (value: number): string =>
  value <= 0 ? "—" : over(value, CONTRA_MOTION_BOUNDS.spread, 2);

const where = (r: MotionStats): string =>
  r.handSpeed.dancer === undefined
    ? "—"
    : `\`${r.handSpeed.dancer}\` ${r.handSpeed.side} at beat ${r.handSpeed.beat!.toFixed(3)}`;

/** Re-exported so a caller can format one report without this file's layout. */
export { formatMotionReport };
export type { MotionReport };
