import type { Vec2 } from "@caller/core";
import type { DancerId } from "../dialect/Dialect.js";
import type { Hand, HoldId } from "../ir/Hold.js";

/**
 * The assembly (D3, D13, DA8): one slot per dancer per beat, hands at the
 * half beat, generated by the scheduler and never hand-written except for
 * intrinsics. The executor turns these into continuous motion; nothing above
 * the executor ever places a point.
 */
export type Instr =
  /** The hip's target at the end of this beat; one per beat, length ≤ `MAX_STEP_CM`. */
  | { op: "step"; foot: Foot; to: Vec2; lengthCm: number }
  /** Facing change over this beat, signed degrees. */
  | { op: "pivot"; deg: number }
  /**
   * A one-beat ramp starting here, **one shared line between the two dancers**:
   * the scheduler emits the same instruction into both programs at the same
   * half beat.
   */
  | { op: "hold"; hand: Hand; with: DancerId; hold: HoldId }
  /** A one-beat ramp to the hang point. */
  | { op: "drop"; hand: Hand }
  /** Target lean in degrees, ramped over the beat. */
  | { op: "lean"; deg: number }
  /** Where the head goes: a dancer (their head), a direction, or down with the bow. */
  | { op: "look"; at: LookAt }
  /** Two steps this beat instead of one (a swing's buzz). */
  | { op: "buzz"; on: boolean }
  | { op: "stand" };

export type Foot = "L" | "R";

export type LookAt = DancerId | { deg: number } | "down";

export type WindowName = "entry" | "body" | "exit";

/** One beat (or half beat) of one dancer's program. */
export interface Slot {
  beat: number;
  half: 0 | 1;
  instrs: readonly Instr[];
  /** The compiled call whose window this slot lies in. */
  call: number;
  window: WindowName;
}
